### ISSUE TITLE
Embla could use more defensive programming...

### ISSUE THREAD

**Issue by adrianlmm** [emilniklas/embla#7]
Greetings.

I've checked the code and I see many good things in Embla, kudos. but I see that it could use more defensive programming, for example:

There is no optional typing for this:

```
get embla => [
  new HttpBootstrapper(
    pipeline: pipe(() => 'Hello world!')
  )
];


```

So, it could also be used like:

`get embla => [1]`

It will crash the code instantly since  in bootstrap.dart in lines from 45 to 47

```
return library
      .getField(#embla)
      .reflectee as List<Bootstrapper>;

```

First it should be a way to check before to see if #embla can be casted to "List<Bootstrapper>" before casting it or consider surround it with try..catch.

Also. in the documentation you could add something like, to avoid casting errors.

```
get embla => <Bootstrapper>[
  new HttpBootstrapper(
    pipeline: pipe(() => 'Hello world!')
  )
];

```

Keep it up with the good work.

**Comment by emilniklas** [comment]
Hi, @adrianlmm!

You make a good point. I'm all for defensive programming and nice error messages and so on.

Writing `get embla => []` is like writing `main() {}`, and just like you can optionally write `void main() {}`, you can do `List<Bootstrapper> get embla => []` or even `<Bootstrapper>[]` like in your example.

The reason why I don't have that in the docs, is because to get access to the `Bootstrapper` type you must import `package:embla/application.dart`, which is completely unnecessary if you don't implement any own bootstrappers.

Such a core part of the framework should not really be a real issue. I mean why on earth would you put in `get embla => [1]`?

**Comment by adrianlmm** [comment]
I do understand that you favor simplicity, is OK, but I believe that the error: "Class 'whatever' has no instance method '_run'." tells nothing and is confusing, and using better error messages raise the quality of the framework, people will actually won't do a  get embla => [1] , but just sustitute the number 1 with any other stuff and the result is the same, I did that just to illustrate the problem.

And I don't see any problem importing other library, since two libraries are already there.

export 'package:embla/bootstrap.dart';
import 'package:embla/http.dart';

A solution would be to move Bootstrapper to other place.

**Comment by emilniklas** [comment]
Yeah. The error can definitely be much better. I will look into this

**Comment by emilniklas** [comment]
This issue has been addressed in the `develop` branch and will be included in the next release.

https://github.com/dart-embla/embla/commit/e04cbf8b94a72b757d2ee488ade601afb8a0a15b
